version: '3.9'

services:
  db:
    image: postgres:15-alpine
    ports:
      - ${POSTGRES_EXPOSE_PORT}:5432
    
    environment:
      - TZ: "${POSTGRES_TZ}"
      - POSTGRES_USER: "${POSTGRES_USER}"
      - POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      - POSTGRES_DB: "${POSTGRES_DB}"
    
    volumes:
      - ./data/db:/var/lib/postgresql/data/
